language: objective-c
rvm: 1.9.3
before_install: 
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-ri --no-rdoc

before_script:
  - brew update
  - brew uninstall xctool
  - brew install xctool
  - pod repo add artsy https://github.com/artsy/Specs.git

xcode_workspace: UnitTests.xcworkspace
xcode_scheme: UnitTests
xcode_sdk: iphonesimulator
